language: haskell

install:
    - cabal update
    - cabal install --force-reinstalls hspec cabal-meta cabal-src alex
    - cabal-meta install --force-reinstalls

script:
    - echo Done
    - cabal-meta install --enable-tests
    - mega-sdist --test
    - cabal install hspec cabal-meta cabal-src
    - cabal-meta install --force-reinstalls
